name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-14.2

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: |
          xcodebuild clean test -project PlantingMind/PlantingMind.xcodeproj -scheme PlantingMind -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1'
