name: Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and Test
        run: |
          xcodebuild clean test -project PlantingMind/PlantingMind.xcodeproj -scheme PlantingMind -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2'
